## Load user, vhost, queue, etc. definitions from a file.
load_definitions = /etc/rabbitmq/definitions.json

## Allow the default 'guest' user to log in from remote hosts (e.g., your browser)
## For development environments only.
loopback_users = none
